### ISSUE TITLE
revive point doesn't revive

### ISSUE THREAD

**Issue by embermctillhawk** [den3606/holy_mountain_revive_point#10]
Possible load order issue?

Installed this mod a few days ago. It worked one time a few days ago, and failed to work twice now in the last 24 hours.
I don't remember what the damage source was that worked.

Failed to revive from omega sawblade, and failed to revive from the heartbreak wizard projectile.

If this mod needs to be first or last, please advise.

**Comment by den3606** [comment]
@embermctillhawk 
Thank you for your report!

I have not encountered such a bug myself due to the infrequent use of this mod.
If possible, I would appreciate it if you could provide a list of the mods you were using at the same time.

**Comment by den3606** [comment]
>Possible load order issue?

Mods that may have an impact are mods that make some changes to the Entity of the player.

- I have never encountered this problem.
- I fixed the revival is not triggered when processing some polymorphic forms.
- The source code has changed significantly between the time of writing and now.

For these reasons, I am closing this issue.
