### ISSUE TITLE
Mod not working on Noita GOG

### ISSUE THREAD

**Issue by fdzgallen** [den3606/holy_mountain_revive_point#12]
Hey first of all thanks for the mod. I am runing Noita build Jun 19 2023.

I downloaded and manually installed the mod for Noita from GOG store. Simply unpacked the ZIP in the mod directory.

The mod config inside the game shows, chosing the price for revival and wheter it scales linearly or exponentially etc.  However when I start a new game a text message in red appears saying "There were errors when initializing the following mods: holy_mountain_revive_point - main"

When I reach the holy mountain there is no revive point. Is the only mod I'm running dont know if I have to do anything else for installation?

Thanks

**Comment by den3606** [comment]
I didn't notice your comment, sorry.
 Since things have changed since then, could you please DL and try again?
 One problem that often occurs when downloading a zip file is that the file name is different from the mod name.
 Please try after renaming the file to the name of this mod.
